name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
    buid:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
                os: [ubuntu-latest]
                arch: [amd64]

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Set up NodeJS ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          env:
            PUPPETEER_SKIP_CHROMIUM_DONLOAD: true
          with:
            node-version: ${{ matrix.node-version }}
        
        - name: Install Dependencies
          run: npm install

        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerexample: latest
            file: Dockerfile
            
        - name: Image digest\
          un: echo ${{ steps.docker_build.outputs.digest }}